# E:\MEDPRIME\.github/workflows/docker-build.yml
name: Docker Build and Publish

on:
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: atharv1398  # Replace with your Docker Hub username
          DOCKER_TOKEN: dckr_pat_yNzQiiiHk2UcRNgXM0UImzf1poU  # Replace with your Docker Hub personal access token
        run: |
          docker buildx create --use
          echo "$DOCKER_TOKEN" | docker login -u $DOCKER_USERNAME --password-stdin
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ github.repository }}:${{ github.sha }} -t ${{ github.repository }}:latest .
          docker push ${{ github.repository }}:${{ github.sha }}
          docker push ${{ github.repository }}:latest
